# Config for cargo-dist
[dist]
# The preferred cargo-dist version to use
cargo-dist-version = "0.11.1"

# CI backends to support
ci = ["github"]

# Target platforms to build for
targets = [
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]

# Installers to generate
installers = ["shell", "powershell", "homebrew", "npm"]

# Enable additional release features
publish-jobs = ["homebrew", "npm"]
pr-run-mode = "plan"
allow-dirty = ["ci"]

[dist.github-custom-runners]
aarch64-unknown-linux-gnu = "buildjet-2vcpu-ubuntu-2204-arm"
aarch64-unknown-linux-musl = "buildjet-2vcpu-ubuntu-2204-arm"